import Head from "next/head";
import { useState } from "react";
import About from "./components/About";
import Header from "./components/Header";
import Navbar from "./components/Navbar";

export default function Home({ data }) {
  const [darkMode, setDarkMode] = useState(false);

  function handleToggleDarkMode() {
    setDarkMode((prevDarkMode) => !prevDarkMode);
  }
  return (
    <div>
      <Head>
        <title>Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar darkMode={darkMode} toogleDarkMode={handleToggleDarkMode} />
        <Header darkMode={darkMode} />
        <About data={data} darkMode={darkMode} />
      </main>
    </div>
  );
}

export function getStaticProps() {
  const data = [
    {
      id: 1,
      title: "Frontend developer",
      description:
        "As a frontend developer, I've focused on learn, use, and enjoy Reactjs, Nextjs, Vanilla JavaScript, CSS, SCSS, and Tailwindcss. I'm completily obsesed with these technologies",
      imageUrl: "/v1656451155/portfolio/aboutMe_x35gtb.png",
      alt: "Representative image for frontend developer.",
    },
    {
      id: 2,
      title: "Backend developer",
      description:
        "I've always been interested in the backend ecosystem. Since I worked with nodejs I knew that the backend was for me. Currently I'm working on Nodejs, but I've also worked with .Net framework and .Net Core.",
      imageUrl: "/v1656455452/portfolio/Completed_task__Outline_khmkce.png",
      alt: "Representative image for frontend developer",
    },
  ];

  return {
    props: {
      data,
    },
  };
}
